### ISSUE TITLE
Fix uppercase letters not working

### ISSUE THREAD

**Issue by dylan-chong** [dictation-toolbox/aenea-grammars#9]
I have these vim grammars

```
        'open': Key('o'),
        'big open': Key('O'),
```

but whether I say open or big open (these are understood correctly by Dragon), only a lower case `o` is pressed.

It appears you have to use `s-o` instead of `O`

**Comment by dylan-chong** [comment]
I can make a PR with these changes to the vim grammar if whoever is in charge is ok with changing this

**Comment by dylan-chong** [comment]
@calmofthestorm Do you agree that I should make these changes? (I have made them to the vim grammars on my fork)

**Comment by dylan-chong** [comment]
Have you encountered the problem I have described? I find it unusual that so much of this grammar has been added, so it must have worked at some point, yet it does not work on my setup.

**Comment by calmofthestorm** [comment]
I don't recall having this problem personally, but I seldom dictate individual keystrokes so it's entirely possible I never used that command. And given our testing story is...basically nonexistent, I'm not surprised to keep finding bugs like this.

These days most of my use is the prose capture client; I've mostly gone back to coding by keyboard due to the joy of open office floorplans.

**Comment by dylan-chong** [comment]
Ah if the testing is poor, I guess I can agree with you that this is bug has been here for a while.

I will put this on my TODO list, and get it done ... sometime ...

**Comment by dylan-chong** [comment]
`Text('TeStInG')` seems enter capital letters perfectly fine now. Perhaps it was something to do with the vim grammar (I mustn't have been testing it in relative isolation).
